SELECT LISTAGG ('"' || DATA || '"', ',')  WITHIN GROUP (ORDER BY ROWNUM) MESES
FROM (SELECT TO_CHAR(ADD_MONTHS(INICIO, LEVEL), 'MM/YYYY') DATA
        FROM (SELECT ADD_MONTHS(TO_DATE('01/01/2018','DD/MM/YYYY'),-1) INICIO,
                     TO_DATE('31/12/2018','DD/MM/YYYY') FIM
                FROM DUAL)
CONNECT BY LEVEL <= MONTHS_BETWEEN(TRUNC(FIM, 'MM'), TRUNC(INICIO, 'MM')) * 1);