SELECT SYSDATE + INTERVAL '10' SECOND FROM DUAL;
SELECT SYSDATE + INTERVAL '10' MINUTE FROM DUAL;
SELECT SYSDATE + INTERVAL '10' HOUR FROM DUAL;
SELECT SYSDATE + INTERVAL '10' DAY FROM DUAL;
SELECT SYSDATE + INTERVAL '10' MONTH FROM DUAL;
SELECT SYSDATE + INTERVAL '10' YEAR FROM DUAL;