SELECT LISTAGG ('"' || DATA || '"', ',')  WITHIN GROUP (ORDER BY ROWNUM) DIAS
  FROM (SELECT TO_CHAR((INICIO + LEVEL), 'DD/MM/YYYY') DATA
          FROM (SELECT ADD_MONTHS((LAST_DAY(SYSDATE)),-1) INICIO,
                       LAST_DAY(SYSDATE) FIM
                  FROM DUAL)
CONNECT BY LEVEL <= (FIM - INICIO) * 1);