SELECT SUM(BYTES) / 1024 / 1024 SIZE_IN_MB, TABLESPACE_NAME
  FROM DBA_DATA_FILES
 GROUP BY TABLESPACE_NAME
UNION ALL
SELECT SUM(BYTES) / 1024 / 1024 SIZE_IN_MB, 'TOTAL'
  FROM DBA_DATA_FILES
  ORDER BY 1 ASC;

SELECT SUM(BYTES) / 1024 / 1024 SIZE_MB, OWNER
  FROM DBA_SEGMENTS
 GROUP BY OWNER
UNION ALL
SELECT SUM(BYTES) / 1024 / 1024 SIZE_IN_MB, 'TOTAL'
  FROM DBA_SEGMENTS ORDER BY 1 ASC;