--Job DDL
SELECT DBMS_METADATA.GET_DDL('PROCOBJ', JOB_NAME) JOB_DDL, 
       JOB_NAME
  FROM USER_SCHEDULER_JOBS
 WHERE JOB_NAME = 'JOB_NAME';


--View DDL
SELECT DBMS_METADATA.GET_DDL('VIEW', VIEW_NAME) DDL_VIEW, VIEW_NAME
  FROM ALL_VIEWS
 WHERE VIEW_NAME = 'VIEW_NAME';