DECLARE

V_TESTE VARCHAR2(200);
V_TESTE2 VARCHAR2(200);

BEGIN

RAISE NO_DATA_FOUND;

EXCEPTION
	WHEN NO_DATA_FOUND THEN

	  V_TESTE := DBMS_UTILITY.FORMAT_ERROR_BACKTRACE || 'ERROR:' ||  SQLERRM;
    V_TESTE2 := DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
    
    DBMS_OUTPUT.PUT_LINE(V_TESTE);
    DBMS_OUTPUT.PUT_LINE(SUBSTR(V_TESTE2,LENGTH(V_TESTE2)-1,1));

END; 