SELECT 'GRANT ' || T.PRIVILEGE || ' ON ' || T.OWNER || '.' || T.TABLE_NAME ||
       ' TO ' || T.GRANTEE ||
       DECODE(GRANTABLE, 'YES', ' WITH GRANT OPTION', 'NO', NULL) || ';' "GRANT"
  FROM DBA_TAB_PRIVS T
 WHERE GRANTEE = 'SCHEMA'
