--Todos os objetos inválidos
SELECT OWNER, OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM DBA_OBJECTS
 WHERE STATUS = 'INVALID'
   AND OWNER LIKE 'SCHEMA_NAME'
   AND OBJECT_TYPE IN ('PACKAGE','PACKAGE BODY'); --Tipo do Objeto

--Recompilar o schema inteiro
BEGIN

  DBMS_UTILITY.COMPILE_SCHEMA(SCHEMA => 'SCHEMA_NAME');

END;
 

-- Compiling a package; 
ALTER PACKAGE SCHEMA.SCHEMA_OBJECT COMPILE; 
ALTER PACKAGE SCHEMA.SCHEMA_OBJECT COMPILE BODY;
 
-- Compiling a procedure: 
ALTER PROCEDURE SCHEMA.SCHEMA_OBJECT COMPILE;
 
-- Compiling a view: 
ALTER VIEW SCHEMA.SCHEMA_OBJECT COMPILE;
 
-- Compiling a function: 
ALTER FUNCTION SCHEMA.SCHEMA_OBJECT COMPILE;