SELECT SID, 
       SERIAL#, 
       SQL_TEXT, 
       USERS_EXECUTING, 
       USER_IO_WAIT_TIME, 
       VS.*
FROM V$SQLAREA V,
     V$SESSION VS
WHERE VS.SQL_ID = V.SQL_ID 
AND USERNAME = 'USER'
AND SID = 000;