BEGIN

  FOR I IN (SELECT * FROM PKLIST WHERE PL_BARCODE = '01071') LOOP
  
    UPDATE SI
       SET SI_RES = SI_RES - I.PL_QTYPICKED
     WHERE SI_ID = I.PL_SISKSIID;
     
    DELETE FROM PKLIST WHERE PL_ID = I.PL_ID;
  
  END LOOP;

  UPDATE REQUEST SET RQ_STATUS = 1 WHERE RQ_ID = 6232;
  
  COMMIT;

END;
