SELECT 'DROP SEQUENCE ' || SEQUENCE_NAME || ';'
  FROM ALL_SEQUENCES
 WHERE SEQUENCE_OWNER = 'I9_UIW'
UNION ALL
SELECT 'CREATE SEQUENCE ' || SEQUENCE_NAME || ' MINVALUE ' || MIN_VALUE ||
       ' MAXVALUE ' || MAX_VALUE || ' START WITH ' || MIN_VALUE ||
       ' INCREMENT BY ' || INCREMENT_BY || ' NOCACHE ' ||
       DECODE(CYCLE_FLAG, 'N', NULL, 'Y', 'CYCLE') || ';'
  FROM ALL_SEQUENCES
 WHERE SEQUENCE_OWNER = 'I9_UIW'