SELECT MENOR_VALOR - 1 + LEVEL
  FROM (SELECT MIN(SEQUENCIA) MENOR_VALOR, MAX(SEQUENCIA) MAIOR_VALOR
          FROM TABELA)
CONNECT BY LEVEL <= MAIOR_VALOR - MENOR_VALOR + 1
MINUS
SELECT SEQUENCIA
  FROM TABELA
