SELECT 'CREATE OR REPLACE ' || DECODE(OWNER, 'PUBLIC', 'PUBLIC', NULL) ||
       ' SYNONYM ' || SYNONYM_NAME || ' FOR ' || TABLE_OWNER || '.' ||
       TABLE_NAME || ';' "CREATE"
  FROM ALL_SYNONYMS a
 WHERE TABLE_OWNER LIKE UPPER('%SCHEMA%');
