--Criar tipo WS_HEADER--

CREATE OR REPLACE TYPE WS_HEADER AS OBJECT

(
  HEADER_KEY VARCHAR2(4000),
  HEADER_VALUE CLOB
)



--Criar tipo WS_HEADER_ARRAY--

CREATE OR REPLACE TYPE WS_HEADER_ARRAY IS TABLE OF WS_HEADER



--Exemplo de Uso--

DECLARE

  HEADERS WS_HEADER_ARRAY := WS_HEADER_ARRAY();

BEGIN

  HEADERS := WS_HEADER_ARRAY(NULL);
  HEADERS.EXTEND(7);
  HEADERS(1) := WS_HEADER('CHAVE 1', 'VALOR 1');
  HEADERS(2) := WS_HEADER('CHAVE 2', 'VALOR 2');
  HEADERS(3) := WS_HEADER('CHAVE 3', 'VALOR 3');
  HEADERS(4) := WS_HEADER('CHAVE 4', 'VALOR 4');
  HEADERS(5) := WS_HEADER('CHAVE 5', 'VALOR 5');
  HEADERS(6) := WS_HEADER('CHAVE 6', 'VALOR 6');
  HEADERS(7) := WS_HEADER('CHAVE 7', 'VALOR 7');
  HEADERS(8) := WS_HEADER('CHAVE 8', 'VALOR 8');

  FOR I IN 1 .. HEADERS.COUNT LOOP
  
    DBMS_OUTPUT.PUT_LINE(HEADERS(I).HEADER_KEY || ' - ' || HEADERS(I).HEADER_VALUE);
  
  END LOOP;

END;
